name: Hello

on:
  push:
    branches:
      - blank
  # pull_request:
  #  branches:
  #    - bugfix-2.0.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Hello
      env:
        FOO_HASH: ${{ hashFiles('**/foo.txt') }}
        DUMMY_HASH: ${{ hashFiles('**/dummy.yml') }}
      run: |
        echo "Hello"
        pwd
        env
        echo $0
        ls -lR $(dirname $0)
        touch nothing.txt
    - name: Oh-no
      env:
        NOTHING_HASH: ${{ hashFiles('**/nothing.txt') }}
      run: |
        env
        
    #- uses: ncipollo/release-action@v1
    #  with:
    #    #artifacts: "release.tar.gz,foo/*.txt"
    #    #bodyFile: "body.md"
    #    artifacts: ".github/workflows/dummy.yml"
    #    token: ${{ secrets.GITHUB_TOKEN }}
    #    prerelease: true
    #    name: unstable
    #    tag: wft-latest
    #    commit: ${{ github.ref }}
    #    allowUpdates: true

    #- uses: actions/create-release@v1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    #tag_name: ${{ github.ref }}
    #    tag_name: wft-latest
    #    release_name: Release ${{ github.ref }}
    #    #body: |
    #    #  Changes in this Release
    #    #  - First Change
    #    #  - Second Change
    #    draft: false
    #    prerelease: true
    # Hmmmm
  conditional:
    runs-on: ubuntu-latest
    needs: build
    if: hashFiles('**/nothing.txt') != hashFiles('**/foo.txt')
    steps:
    - name: Echo something
      run: |
        echo Something
