name: Hello

on:
  push:
    branches:
      - blank

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Hello
      run: |
        echo "Hello"
        pwd
        env
        echo $0
        ls -lR $(dirname $0)

    # https://github.com/marketplace/actions/create-pull-request
    - name: Create report file
      run: date +%s > report.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
        echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
