name: Hello

on:
  push:
    branches:
      - blank
  # pull_request:
  #  branches:
  #    - bugfix-2.0.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Hello
      run: |
        echo "Hello"
        pwd
        env
        echo $0
        ls -lR $(dirname $0)
    - uses: ncipollo/release-action@v1
      with:
        #artifacts: "release.tar.gz,foo/*.txt"
        #bodyFile: "body.md"
        artifacts: ".github/workflows/dummy.yml"
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        name: unstable
        tag: wft-latest
        commit: ${{ github.ref }}
        allowUpdates: true
